namespace: maneyko
name: roles
version: 3.1.0
readme: README.md
authors: [maneyko]
description: Personal Ansible roles
license: [MIT]
repository: https://github.com/maneyko/ansible-roles
issues: https://github.com/maneyko/ansible-roles/issues
tags: [linux, infrastructure, tools]
build_ignore: [.git, .gitignore, .ansible-lint]
